# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/.Xil/Vivado-12948-DESKTOP-18PPVG9/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Button_detect.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Detect.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Display_x7seg.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Mod1_ztj.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Mod2_ztj.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Mod_control.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Negecount1_preset.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Negecount2_60.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Negecount_5.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Negecount_60.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Posecount_30.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Posecount_60.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Preset_num.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Read.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Sec_pulse.v
  C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/sources_1/new/Main_tomato.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/constrs_1/new/project_tomato_CH.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/Vivado/project_tomato_Chuheng/project_tomato_Chuheng.srcs/constrs_1/new/project_tomato_CH.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Main_tomato -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main_tomato.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_tomato_utilization_synth.rpt -pb Main_tomato_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
